### ISSUE TITLE
[PaperUI] Cannot find XMPPlient (Binding) only XMPP Action

### ISSUE THREAD

**Issue by TRSx80** [openhab/openhab-webui#108]
As stated in title, I have searched and searched multiple times but simply cannot find the [XMPPClient](https://www.openhab.org/addons/bindings/xmppclient/) (Binding), only the [XMPP](https://www.openhab.org/addons/actions/xmpp/) (Action), in my PaperUI.

I just recently installed latest OpenHAB 2.4.0 from OpenHAB Stable [Repository](https://openhab.jfrog.io/openhab/openhab-linuxpkg/) on Debian. Platform is armhf.

Aah, bah, just noticed typo in title and cannot edit: s/XMPPlient/XMPPClient

**Comment by TRSx80** [comment]
Aah, bah, just noticed typo in title and cannot edit: s/XMPPlient/XMPPClient

**Comment by openhab-5iver** [comment]
The [XMPPClient 1.x binding](https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.xmppclient) is not in the [feature.xm](https://github.com/openhab/openhab1-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml)l, so nobody has tested it and [taken the steps to move it into the 2.x distribution](https://community.openhab.org/t/poll-which-oh1-x-addons-do-you-use/79121/12?u=5iver).

You can setup an IDE and build the binding or [download the jar](https://ci.openhab.org/job/openhab-milestone/), and copy it to your addons directory. If it works, please open an issue in the [openhab1-addons](https://github.com/openhab/openhab1-addons/issues) repo to let people know that it is working in OH2.

**Comment by TRSx80** [comment]
> The [XMPPClient 1.x binding](https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.xmppclient) is not in the [feature.xm](https://github.com/openhab/openhab1-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml)l, so nobody has tested it and [taken the steps to move it into the 2.x distribution](https://community.openhab.org/t/poll-which-oh1-x-addons-do-you-use/79121/12?u=5iver). That is why you do not see it in Paper UI.
> 
> You can setup an IDE and build the binding or [download the jar](https://ci.openhab.org/job/openhab-milestone/), and copy it to your addons directory. If it works, please open an issue in the [openhab1-addons](https://github.com/openhab/openhab1-addons/issues) repo to let people know that it is working in OH2.

Thanks for the information.

But what should I do if it _doesn't_ work?

```java
23:11:49.361 [ERROR] [org.openhab.binding.xmppclient       ] - FrameworkEvent ERROR - org.openhab.binding.xmppclient
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.xmppclient [200]
  Unresolved requirement: Import-Package: org.openhab.core.automation.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.jivesoftware.smack; version="[4.3.0,5.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
23:11:53.063 [WARN ] [org.apache.felix.fileinstall         ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.xmppclient-2.5.0.M2.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.xmppclient [200]
  Unresolved requirement: Import-Package: org.openhab.core.automation.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.jivesoftware.smack; version="[4.3.0,5.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [10:org.apache.felix.fileinstall:3.6.4]
```

**Comment by openhab-5iver** [comment]
> But what should I do if it doesn't work?

The best option is for you (or someone else) to migrate the binding to OH2.x. The next best option is to setup an earlier version of OH that can use the binding and communicate with a newer version of OH, and then sync data between them.

Take a look at the forum discussions below, which would be much better places for further discussion, as this is not the right repo and you may be able to drum up interest from other users or developers that might want to help with the migration of this binding.

https://community.openhab.org/t/removal-of-the-oh-1-x-compatibility-layer/67553
https://community.openhab.org/t/oh-1-x-add-on-assessment/79334
https://community.openhab.org/t/poll-which-oh1-x-addons-do-you-use/79121
