### ISSUE TITLE
[BasicUI] ClassCastException -> DefaultImpl  cannot be LinkableWidget 

### ISSUE THREAD

**Issue by ODINServ** [openhab/openhab-webui#1098]
## Which UI are you reporting an issue for?

- [ ] Basic UI

## The problem

I'd placed a "Default" item inside a Frame wish is not allowed but it now throws a stack trace.

If i change the "Default" item to for example a "Switch" then the stack trace is the same but then it is a SwitchImpl instead of DefaultImpl  

## Expected behavior

I can remember i made this error before, but then i thought i got an "normal" error instead of a stack trace.

## Steps to reproduce

Snippet of faulty sitemap:
```
sitemap shutters label="shutters"
{
    Frame label="Alle luiken" {
        Default item=Shutters_Button_Bedroom
        Text label="Program" {
            Switch item=Shutters_Automatic_Up
            Switch item=Shutters_Automatic_Down
            Text label="Down Parameters" {
                Switch item=Shutters_Automatic_Down_FirstFloor
                Switch item=Shutters_Automatic_Down_GroundFloor
                Setpoint item=Shutters_Automatic_Down_IgnoreValue minValue=0 maxValue=100 step=10
            }
        }
 << snip >>
```

Snippet of correct sitemap:
```
sitemap shutters label="shutters"
{
    Frame label="Alle luiken" {
        Text label="Program" {
            Default item=Shutters_Button_Bedroom
            Switch item=Shutters_Automatic_Up
            Switch item=Shutters_Automatic_Down
            Text label="Down Parameters" {
                Switch item=Shutters_Automatic_Down_FirstFloor
                Switch item=Shutters_Automatic_Down_GroundFloor
                Setpoint item=Shutters_Automatic_Down_IgnoreValue minValue=0 maxValue=100 step=10
            }
        }
 << snip >>

```

## Your environment

(I'm running openhab 3.1.0M5 in a docker container.)

```yaml
runtimeInfo:
  version: 3.1.0.M5
  buildString: Milestone Build
locale: nl-NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 4.18.0-305.el8.x86_64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 41058312
  totalMemory: 310378496
bindings:
  - astro
  - dsmr
  - exec
  - kodi
  - logreader
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - rfxcom
  - unifi
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: nl
    languages:
      - nl
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101
    Firefox/89.0
timestamp: 2021-06-09T11:04:45.947Z

```

## Browser console

```txt

2021-06-09 12:49:24.691 [ERROR] [ab.core.service.AbstractWatchService] - Error handling update of file '/openhab/conf/sitemaps/shutters.sitemap': class org.openhab.core.model.sitemap.sitemap.impl.DefaultImpl cannot be cast to class org.openhab.core.model.sitemap.sitemap.LinkableWidget (org.openhab.core.model.sitemap.sitemap.impl.DefaultImpl and org.openhab.core.model.sitemap.sitemap.LinkableWidget are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @13f92dac).
java.lang.ClassCastException: class org.openhab.core.model.sitemap.sitemap.impl.DefaultImpl cannot be cast to class org.openhab.core.model.sitemap.sitemap.LinkableWidget (org.openhab.core.model.sitemap.sitemap.impl.DefaultImpl and org.openhab.core.model.sitemap.sitemap.LinkableWidget are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @13f92dac)
        at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.getWidget(ItemUIRegistryImpl.java:639) ~[?:?]
        at org.openhab.core.io.rest.sitemap.SitemapSubscriptionService.collectWidgets(SitemapSubscriptionService.java:269) ~[?:?]
        at org.openhab.core.io.rest.sitemap.SitemapSubscriptionService.modelChanged(SitemapSubscriptionService.java:320) ~[?:?]
        at org.openhab.core.model.sitemap.internal.SitemapProviderImpl.modelChanged(SitemapProviderImpl.java:106) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:301) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:139) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:249) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:312) ~[?:?]
        at org.openhab.core.service.WatchQueueReader.lambda$3(WatchQueueReader.java:322) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ODINServ** [comment]
Well apparently my analysis is wrong, it seems that i did not save the .items file...

Which means that both sitemaps in my bug report above are correct, but apparently in the in my impression "correct" sitemap does not trigger this error.

So steps to reproduce are these sitemaps above but then the "Shutters_Button_Bedroom" item does not exist in the system.

**Comment by lolodomo** [comment]
The stack trace shows an exception in the core framework. Nothing related to BasicUI.

**Comment by ODINServ** [comment]
Ah oke, is it possible to move it or should i repost the bug report there ?

**Comment by lolodomo** [comment]
No need to move it as it is UI stuff. 
I just think you should not link it so hard to BasicUI. 
Can you please check with another UI implementing sitemap like the Android app for example ? I assume you could have the same exception. 
If I am right, just mention "any UI implementing sitemap" rather than focussing on BasicUI.

**Comment by lolodomo** [comment]
Very confusing

Can you please edit your first messages and explain what is wrong in your opinion? 
I guess but I am not sure that your initial message is fully wrong?

**Comment by lolodomo** [comment]
No feedback
