### ISSUE TITLE
Can't start main UI dev server

### ISSUE THREAD

**Issue by niwla23** [openhab/openhab-webui#1443]
## The problem
I cloned this repo, changed to bundles/org.openhab.ui/web, ran npm install and then npm start.
But npm start fails with this output:
```

> openhab@3.0.0 start
> npm run dev


> openhab@3.0.0 dev
> cross-env NODE_ENV=development webpack-dev-server --config ./build/webpack.config.js

[HPM] Proxy created: [
  '/auth',
  '/rest',
  '/chart',
  '/proxy',
  '/icon',
  '/static',
  '/changePassword',
  '/createApiToken'
]  ->  http://localhost:8080
ℹ ｢wds｣: Project is running at http://localhost:8081/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /www/
ℹ ｢wds｣: 404s will fallback to /index.html
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
ℹ ｢wdm｣: wait until bundle finished: /
/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/chokidar.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/DirectoryWatcher.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watcherManager.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watchpack.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/webpack.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack-dev-server/bin/webpack-dev-server.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/chokidar.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/DirectoryWatcher.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watcherManager.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watchpack.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/webpack.js
- /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack-dev-server/bin/webpack-dev-server.js

    at Object.<anonymous> (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at WatcherManager.getDirectoryWatcher (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watcherManager.js:14:25)
    at WatcherManager.watchFile (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watcherManager.js:28:14)
    at Watchpack.<anonymous> (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watchpack.js:38:49)
    at Array.map (<anonymous>)
    at Watchpack.watch (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/watchpack/lib/watchpack.js:37:28)
    at NodeWatchFileSystem.watch (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/node/NodeWatchFileSystem.js:70:16)
    at Watching.watch (/mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/Watching.js:114:48)
    at /mnt/ssd2/Code/openhab-webui/bundles/org.openhab.ui/web/node_modules/webpack/lib/Watching.js:101:10
```

## Expected behavior

start up normally

## Steps to reproduce

1. 

## Your environment

```yaml
██████████████████  ████████   alwin@alwin-pc 
██████████████████  ████████   -------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: HP Compaq Elite 8300 MT 
████████            ████████   Kernel: 5.10.123-1-MANJARO 
████████  ████████  ████████   Uptime: 3 hours, 29 mins 
████████  ████████  ████████   Packages: 2715 (pacman), 45 (flatpak) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 1680x1050, 1920x1080, 1680x1050 
████████  ████████  ████████   DE: Plasma 5.24.5 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   WM Theme: ActiveAccentDusk 
████████  ████████  ████████   Theme: ReversalDark [Plasma], Adwaita-dark [GTK3] 
████████  ████████  ████████   Icons: Fluent-dark [Plasma], Fluent-dark [GTK2/3] 
                               Terminal: vscode 
                               CPU: Intel i5-3570 (4) @ 3.800GHz 
                               GPU: NVIDIA GeForce GTX 1050 
                               Memory: 8071MiB / 15950MiB 

```

## Browser console

```txt
does not apply
```

## Browser network traffic

does not apply
## Additional information

none

**Comment by wborn** [comment]
It works for me after running: `npm update --force`

But it would be nicer if it works for everyone without having to do this manually.

**Comment by ghys** [comment]
I could reproduce this problem - `npm i chokidar` did the trick for me; so you might want to try this too.
I was oblivious to this because my dependencies in `node_modules` were somehow ok.
Maybe do a `npm i --save-dev chokidar` and commit the result could solve this issue for good. If so a PR will follow.

**Comment by bgsPortal** [comment]
I have the same problem as the initial post with the same first 3 steps to take to reproduce (downloaded zip file instead of git clone) and `npm run dev` / `npm start` but with a different output which is

I see a `.gihub` folder only in `openhab-webui-main` directory

```
> openhab@4.2.0 predev
> cross-env NODE_ENV=development npm run generate-build-info


> openhab@4.2.0 generate-build-info
> node build/generate-build-info.mjs

node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128,
  killed: false,
  signal: null,
  cmd: 'git rev-parse --short HEAD',
  stdout: '',
  stderr: 'fatal: not a git repository (or any of the parent directories): .git\n'
}
```
