### ISSUE TITLE
Build error with gulp

### ISSUE THREAD

**Issue by BasvanH** [openhab/openhab-webui#1660]
## Which UI are you reporting an issue for?

HABPanel

## The problem
When I build with gulp, I get an error.

```
gulp
[10:04:41] Using gulpfile ~\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\gulpfile.js
[10:04:41] Starting 'default'...
[10:04:41] Starting 'vendor'...
[10:04:41] Starting 'vendor-js'...
[10:04:41] Starting 'uglify-timeline'...
[10:04:41] Finished 'uglify-timeline' after 493 ms
[10:04:41] Starting '<anonymous>'...
[10:04:41] '<anonymous>' errored after 73 ms
[10:04:41] Error: File not found with singular glob: /Openhab/openhab-webui/bundles/org.openhab.ui.habpanel/web/bower_components/event-source-polyfill/eventsource.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob.EventEmitter.emit (domain.js:448:20)
    at Glob._finish (\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\node_modules\glob\glob.js:194:8)
    at done (\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\node_modules\glob\glob.js:179:14)
    at Glob._processSimple2 (\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\node_modules\glob\glob.js:688:12)
    at \Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\node_modules\glob\glob.js:676:10
    at Glob._stat2 (\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\node_modules\glob\glob.js:772:12)
    at lstatcb_ (\Openhab\openhab-webui\bundles\org.openhab.ui.habpanel\web\node_modules\glob-stream\node_modules\glob\glob.js:764:12)
[10:04:41] 'vendor-js' errored after 574 ms
[10:04:41] 'vendor' errored after 577 ms
[10:04:41] 'default' errored after 584 ms
```

## Expected behavior

A successful build.

## Your environment

Using VSCode on Windows 10.

Using origin/main (24-01-2023) of this repo.

node --version
v10.24.1
bower --version
1.8.14
gulp --version
CLI version: 2.3.0
Local version: 4.0.2
python2 --version
Python 2.7.18

**Comment by BasvanH** [comment]
Latest version of `event-source-polyfill` is installed in `bower_components`: 1.0.24

**Comment by BasvanH** [comment]
Any update on this matter? It has been open for a while.
