### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by arins** [openhab/openhab-webui#1702]
## The problem

1. If i go into an item from items view.
2. deleted it the item i opened
3. go back (back arrow in the UI) 
4. Trying to search again and the search is broken. get following error in console:
![image](https://user-images.githubusercontent.com/1004420/218315266-87b2111f-46c5-415e-90cd-061f1f332cee.png)

## Expected behavior
Be able to search even if i "go back" in the UI

## Steps to reproduce
1. If i go into an item from items view.
2. deleted it the item i opened
3. go back (back arrow in the UI) 
4. Trying to search again and the search is not working 

## Your environment
Openhab 3.4.1
Windows 11 chrome latest

## Browser console

```
/icon/heating%20?format=svg&anyFormat=true:1          Failed to load resource: the server responded with a status of 404 ()
/icon/heating%20?format=svg&anyFormat=true:1          Failed to load resource: the server responded with a status of 404 ()
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
/icon/heating%20?format=svg&anyFormat=true:1          GET https://openhab.sinabian.se/icon/heating%20?format=svg&anyFormat=true 404
Image (async)
ga @ app.eab2460dc8b652f1fc46.js:7
va @ app.eab2460dc8b652f1fc46.js:7
ma @ app.eab2460dc8b652f1fc46.js:7
S @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
e._update @ app.eab2460dc8b652f1fc46.js:7
a @ app.eab2460dc8b652f1fc46.js:7
fn.get @ app.eab2460dc8b652f1fc46.js:7
fn.run @ app.eab2460dc8b652f1fc46.js:7
pn @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
Ze @ app.eab2460dc8b652f1fc46.js:7
Promise.then (async)
Ye @ app.eab2460dc8b652f1fc46.js:7
at @ app.eab2460dc8b652f1fc46.js:7
e.$nextTick @ app.eab2460dc8b652f1fc46.js:7
updated @ app.eab2460dc8b652f1fc46.js:35
qe @ app.eab2460dc8b652f1fc46.js:7
tn @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
pn @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
Ze @ app.eab2460dc8b652f1fc46.js:7
Promise.then (async)
Ye @ app.eab2460dc8b652f1fc46.js:7
at @ app.eab2460dc8b652f1fc46.js:7
e.$nextTick @ app.eab2460dc8b652f1fc46.js:7
beforeDestroy @ app.eab2460dc8b652f1fc46.js:12
qe @ app.eab2460dc8b652f1fc46.js:7
tn @ app.eab2460dc8b652f1fc46.js:7
e.$destroy @ app.eab2460dc8b652f1fc46.js:7
destroy @ app.eab2460dc8b652f1fc46.js:7
w @ app.eab2460dc8b652f1fc46.js:7
k @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
S @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
e._update @ app.eab2460dc8b652f1fc46.js:7
a @ app.eab2460dc8b652f1fc46.js:7
fn.get @ app.eab2460dc8b652f1fc46.js:7
fn.run @ app.eab2460dc8b652f1fc46.js:7
pn @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
Ze @ app.eab2460dc8b652f1fc46.js:7
Promise.then (async)
Ye @ app.eab2460dc8b652f1fc46.js:7
at @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
fn.update @ app.eab2460dc8b652f1fc46.js:7
pe.notify @ app.eab2460dc8b652f1fc46.js:7
set @ app.eab2460dc8b652f1fc46.js:7
$e @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
t.a @ app.eab2460dc8b652f1fc46.js:7
setState @ app.eab2460dc8b652f1fc46.js:23
onPagePosition @ app.eab2460dc8b652f1fc46.js:23
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
value @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
value @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
value @ app.eab2460dc8b652f1fc46.js:7
value @ app.eab2460dc8b652f1fc46.js:7
B @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
(anonymous) @ app.eab2460dc8b652f1fc46.js:7
o @ app.eab2460dc8b652f1fc46.js:1
c @ app.eab2460dc8b652f1fc46.js:1
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
value @ app.eab2460dc8b652f1fc46.js:7
E @ app.eab2460dc8b652f1fc46.js:7
c @ app.eab2460dc8b652f1fc46.js:1
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
value @ app.eab2460dc8b652f1fc46.js:7
E @ app.eab2460dc8b652f1fc46.js:7
c @ app.eab2460dc8b652f1fc46.js:1
app.eab2460dc8b652f1fc46.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'params')
    at s.value (app.eab2460dc8b652f1fc46.js:7:427183)
    at HTMLInputElement.E (app.eab2460dc8b652f1fc46.js:7:418973)
    at HTMLInputElement.c (app.eab2460dc8b652f1fc46.js:1:7713)
value @ app.eab2460dc8b652f1fc46.js:7
E @ app.eab2460dc8b652f1fc46.js:7
c @ app.eab2460dc8b652f1fc46.js:1

```

## Browser network traffic

I dont think this is needed

## Additional information

nothing more

**Comment by arins** [comment]
maybe same as this one: https://github.com/openhab/openhab-webui/issues/1334
