### ISSUE TITLE
[blockly] contextual info new state of item cannot be interpreted as QuantityType

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-webui#1942]
## The problem

Edit: problem is somewhere else, title adjusted and problem description is https://github.com/openhab/openhab-webui/issues/1942#issuecomment-1611078320.

The current quantity computation block only allows 2 arguments with the same dimension.

## Your suggestion

Ideally, for division and multiplication, it should be possible to have a decimal value as a second argument. It is a common use case to multiply/divide a quantity with a constant or calculated value.

## Additional information

As a bonus (but not critical), it would be nice to align the symbols for multiplication and division with the standard ones in the math calculation block.
The quantity computation block uses * and /. The standard block uses × and ÷.

**Comment by mherwege** [comment]
Analyzing further. My problem seems to be somewhere else. I will come back with a more detailed analysis.

**Comment by mherwege** [comment]
Here is the blockly code with the problem:

<img width="501" alt="image" src="https://github.com/openhab/openhab-webui/assets/23501634/ea948342-4a1d-4cfe-80d6-a2afd23c56d4">

Generated js:

```
var pveTodayGS2, pveTodayGS1;


console.info(('New PVETodayGS2: ' + String(event.itemState)));
pveTodayGS2 = event.itemState.quantityState;
console.info(('New PVETodayGS2 Qty: ' + String(pveTodayGS2)));
pveTodayGS1 = (pveTodayGS2.quantityState.multiply((cache.shared.get('RATIO')) * 1));
console.info(('Setting PVETodayGS1 to: ' + String(pveTodayGS1)));
```

And extract from the log failure:

```
2023-06-28 11:25:22.079 [INFO ] [nhab.automation.script.ui.778df0dc03] - New PVETodayGS2: 3.459 kWh
2023-06-28 11:25:22.081 [INFO ] [nhab.automation.script.ui.778df0dc03] - New PVETodayGS2 Qty: undefined
2023-06-28 11:25:22.083 [ERROR] [b.automation.script.javascript.stack] - Failed to execute script:
org.graalvm.polyglot.PolyglotException: TypeError: Cannot read property "quantityState" from undefined
	at <js>.:program(<eval>:7) ~[?:?]
	at org.graalvm.polyglot.Context.eval(Context.java:399) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426) ~[?:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:53) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:78) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:53) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:78) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:71) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:68) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1175) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:984) ~[?:?]
	at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:87) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-06-28 11:25:22.091 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID '778df0dc03' failed: org.graalvm.polyglot.PolyglotException: TypeError: Cannot read property "quantityState" from undefined
```

**Comment by florian-h05** [comment]
I have just checked the Blockly code, and division/multiplication by plain number is supported.

The problem is, that the green Qty block where you put the "contextual info new state of Item" into expects to get an Item when there is no type information provided by Blockly. This is the same problem as you described in your first paragraph. IMHO this can be fixed by setting the output type of the `contextual_info` block https://github.com/openhab/openhab-webui/blob/7cb786aa51d144c095225c6b5c9bd411cc161acb/bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js#L161, I will leave that to Stefan who has much more experience with Blockly. 

The second problem is, that variables in Blockly have no type, and it is assumed that variables passed to Quantity blocks are Items (from openhab-js). I can adjust openhab-js to accept more data types for the Quantity factory, so does run into less type problems with variables.

**Comment by mherwege** [comment]
Am I right that Blockly does not even use the Quantity factory?
In the generated code I see:
```
pveTodayGS2 = event.itemState.quantityState;
```

The event.itemState fed in is `3.459 kWh`. Already, using the Quantity factory would require this to be changed in `3.459 k*W*h` if I understand the documentation well enough.

**Comment by florian-h05** [comment]
event.itemState has no type defined in the Blockly code. The Qty block expects that inputs with no type are openhab-js Item, which have a `quantityState` property. 
I am currently working at modifying the Quantity factory, so it does accept openhab-js Item, then Blockly can always use the Quantity factory and the problem with unknown types is migitiated.

> The event.itemState fed in is 3.459 kWh. Already, using the Quantity factory would require this to be changed to 3.459 k*W*h if I understand the [documentation](https://next.openhab.org/addons/automation/jsscripting/#quantity) well enough.

No, kWh does work. The JS Quantity is using the Java openHAB QuantityType under the hood, everything that is supported by openHAB's QuantityType therefore just works. The problem is, that there are units that aren't accepted in some written notations, I haven't found a scheme behind that.

**Comment by stefan-hoehn** [comment]
Sorry that I am late to the party. Only 3 days ago I noticed this issue. Thanks, @mherwege, finally something more tricky to think about. As always ;-) , @florian-h05  already tracked down the main issue cause pretty nicely. I have now begun to reproduce the issue and will then see what exactly needs to be changed. This is the more simplified rule that I thing reproduces the problem:

<img width="866" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/809537b8-dd23-485b-8228-09a3bad64795">
<img width="567" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/dc11222b-616a-43f9-a814-81e005e75689">

````
var powerQtyVar, PowerResultVar;


console.info(('New Power State' + String(event.itemState)));
powerQtyVar = event.itemState.quantityState;
console.info(('New Power State Qty' + String(powerQtyVar)));
PowerResultVar = (powerQtyVar.quantityState.multiply(10));
console.info(('New Power Result' + String(PowerResultVar)));
````

I'll keep updating this comment during fixing it. Feel free to respond if you notice something I overlook, though.

**Comment by stefan-hoehn** [comment]
With my change it does now generate the following code

````
var powerQtyVar, PowerResultVar;


console.info(('New Power State' + String(event.itemState)));
powerQtyVar = Quantity(event.itemState);
console.info(('New Power State Qty = ' + String(powerQtyVar)));
PowerResultVar = (Quantity(powerQtyVar).multiply(10));
console.info(('New Power Result = ' + String(PowerResultVar)));
````

This requires @florian-h05 in the library as well and solves you problem, @mherwege.

Do we want to go forward with both changes, @florian-h05 ?
