### ISSUE TITLE
[BasicUI] Some material icons missing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2011]
When implementing PR #2010, I discovered that some material icons were missing while they are supposed to exist, like for example this one: https://fonts.google.com/icons?selected=Material+Icons+Outlined:legend_toggle:&icon.set=Material+Icons&icon.query=legend+toggle

The reason could be that we rely on version 3.0.1:
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.basic/package.json#L13

The last version is 4.0.0.
https://github.com/google/material-design-icons/releases/tag/4.0.0

**Comment by lolodomo** [comment]
if I changed the line in package.json to 
```
"material-design-icons": "^4.0.0",
```
Then the build is failing, this version is apparently not found:
```
48 verbose type range
49 verbose stack material-design-icons: No matching version found for material-design-icons@^4.0.0.
49 verbose stack     at module.exports (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
49 verbose stack     at D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\node_modules\pacote\lib\registry.js:126:26
49 verbose stack     at async Arborist.[nodeFromEdge] (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1101:19)
49 verbose stack     at async Arborist.[buildDepStep] (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:970:11)
49 verbose stack     at async Arborist.buildIdealTree (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:216:7)
49 verbose stack     at async Promise.all (index 1)
49 verbose stack     at async Arborist.reify (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
49 verbose stack     at async Install.exec (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\lib\commands\install.js:159:5)
49 verbose stack     at async module.exports (D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic\node\node_modules\npm\lib\cli.js:78:5)
50 verbose cwd D:\dev\openhab3\git\openhab-webui\bundles\org.openhab.ui.basic
51 verbose Windows_NT 10.0.19045
52 verbose node v16.14.2
53 verbose npm  v8.6.0
54 error code ETARGET
55 error notarget No matching version found for material-design-icons@^4.0.0.
56 error notarget In most cases you or one of your dependencies are requesting
56 error notarget a package version that doesn't exist.
57 verbose exit 1
```

Any idea what I am missing ?

**Comment by lolodomo** [comment]
```
$ npm view  material-design-icons -native versions

[ '1.0.0',
  '1.0.1',
  '2.0.0',
  '2.1.0',
  '2.1.1',
  '2.1.3',
  '2.2.0',
  '2.2.1',
  '2.2.2',
  '2.2.3',
  '3.0.0',
  '3.0.1' ]

````
So more recent version is not published on npm repository :-(

**Comment by lolodomo** [comment]
one option to try would be to switch from the official repo to https://github.com/marella/material-icons
