### ISSUE TITLE
[habpanel] Exception thrown using custom widgets in 3.x

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#323]
After importing my habpanel export file to my new 3.x setup, none of my custom widgets work (nothing renders).  I don't think much should have changed in the web app, so i'm not clear what could be breaking this (maybe not 3.x related?) .  The console log shows this stack trace:

```
vendor.js:119 TypeError: Cannot read property 'undefined' of undefined
    at render (http://oh:8080/habpanel/app/widgets/template/template.widget.js:39:45)
    at Object.link (http://oh:8080/habpanel/app/widgets/template/template.widget.js:125:13)
    at http://oh:8080/habpanel/vendor/vendor.js:16:71
    at http://oh:8080/habpanel/vendor/vendor.js:82:187
    at sa (http://oh:8080/habpanel/vendor/vendor.js:82:244)
    at n (http://oh:8080/habpanel/vendor/vendor.js:68:6)
    at g (http://oh:8080/habpanel/vendor/vendor.js:59:428)
    at g (http://oh:8080/habpanel/vendor/vendor.js:59:445)
    at n (http://oh:8080/habpanel/vendor/vendor.js:67:452)
    at g (http://oh:8080/habpanel/vendor/vendor.js:59:428) <widget-template ng-model="vm.previewmodel" class="ng-pristine ng-untouched ng-valid ng-isolate-scope">
....
Show 3 more frames
vendor.js:119 TypeError: Cannot read property 'undefined' of undefined
    at render (template.widget.js:39)
    at template.widget.js:122
    at m.$broadcast (vendor.js:149)
    at settings.widgets.designer.controller.js:69
    at vendor.js:160
    at f (vendor.js:45)
    at vendor.js:48
```

**Comment by ghys** [comment]
This was a feature that never took off of immutable custom widgets defined in the service config outside panel configurations, the idea was to allow them to be bundled in .jar along with static resources/custom JavaScript etc.
Since it depends on `/rest/services/org.openhab.habpanel/config` being accessible it doesn't work anymore, and will be fixed by replacing it with something else - or removing it since nobody uses it - along with #320.
