### ISSUE TITLE
Paper UI: missing patch / customization support

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-webui#53]
At the time we migrate ESH to openHAB Core the decision has been taken to move the Paper UI not to openHAB Core but to this repository.
IIRC we agreed to keep the patch / customization support so it will still be able to use another layout.

Now this support has been removed.

Is my memory deceiving me?
Why has the customization support been removed without any public discussion?

**Comment by kaikreuzer** [comment]
No, there was no decision to remove this support, it just happened to have disappeared by some "fixing the build issues".

**Comment by wborn** [comment]
It now shows the following stacktrace again on the snapshot build:

```
22:43:30.755 [INFO ] [org.openhab.ui.paper                 ] - FrameworkEvent INFO - org.openhab.ui.paper
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; osgi.identity="org.openhab.ui.paper"; type="osgi.bundle"; version:Version="2.5.0.201904112024""
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassPathEntry(ClasspathManager.java:174) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.buildClasspath(ClasspathManager.java:152) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.<init>(ClasspathManager.java:81) ~[?:?]
	at org.eclipse.osgi.internal.loader.EquinoxClassLoader.<init>(EquinoxClassLoader.java:43) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:316) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader$2.run(BundleLoader.java:239) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader$2.run(BundleLoader.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:236) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:595) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getModuleClassLoader(EquinoxBundle.java:588) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getResource(EquinoxBundle.java:530) ~[?:?]
	at org.apache.servicemix.specs.activation.Activator.register(Activator.java:58) ~[?:?]
	at org.apache.servicemix.specs.locator.Activator.bundleChanged(Activator.java:93) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:124) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:122) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:719) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

That's because OH no longer uses this patch.

**Comment by maggu2810** [comment]
That is interesting because I don't see this exception.

> No, there was no decision to remove this support, it just happened to have disappeared by some "fixing the build issues".

> That's because OH no longer uses this patch.

So, has it been removed because of build issues or because of a `BundleExcpetion`?
In both cases it sounds more like it has been removed by intention.

**Comment by wborn** [comment]
Looks like I removed it for Classic UI in https://github.com/openhab/openhab-webui/pull/22. I was not aware this feature was still being used. Looks like it was already removed from the Paper UI manifest in the [initial commit](https://github.com/wborn/openhab-webui/blob/8ed8126084a64e804fe2f57f9a9368842664f3ac/org.openhab.ui.paper/META-INF/MANIFEST.MF). So it also needs to be restored for the other UIs. A test or comment might also prevent it from being removed in the future again.

**Comment by maggu2810** [comment]
Perhaps it does not work in Equinox but in Felix.
Will check that.

I need also to check, if it works, if the host bundle contains an empty patch directory.

**Comment by maggu2810** [comment]
@wborn I tried it in "my" demo app setup that is using Equinox 3.13.100.v20180827-1536.

* The Paper UI is using "patch/,." as bundle classpath and a fragment is used: works (customized)
* The Paper UI is using "patch/,." as bundle classpath and no fragment is used: works (standard)

**Comment by kaikreuzer** [comment]
> So, has it been removed because of build issues or because of a BundleExcpetion?
> In both cases it sounds more like it has been removed by intention.

Yes, removed because of this BundleException. And yes, the intention was to make the UI work again.

With having it reverted again with https://github.com/openhab/openhab-webui/pull/54, it probably means that the current distro builds are broken / not usable? Could we revert it once again until we have figured out how to do add the customisation support properly?

**Comment by maggu2810** [comment]
* I downloaded the most recent version of "openhab-2.5.0-SNAPSHOT.tar.gz" from openHAB Jenkins CI.
* extract archive
* start by using "start.sh"
* ensure SCR and HTTP support is present (`feature:install scr http`)
* install locally build Paper UI

```
openhab> bundle:install file:///home/rathgeb/.m2/repository/org/openhab/ui/bundles/org.openhab.ui.paper/2.5.0-SNAPSHOT/org.openhab.ui.paper-2.5.0-SNAPSHOT.jar
Bundle ID: 200
```

* start bundle

```
openhab> bundle:start 200
```

* check log
* There is a "FrameworkEvent INFO" that the class path entry "patch/" entry is not found
* the Paper UI works as expected

In the default Karaf 4.2.2 distribution the log is not shown, so I assume you increase the log verbosity for framework events.

IMHO there is not need to revert it if it is only about a log message with severity info.

**Comment by wborn** [comment]
>  so I assume you increase the log verbosity for framework events

It seems to be caused by the INFO log level of `org.openhab`. So one way of suppressing the stacktrace could be by setting the log level of `org.openhab.ui.paper` to WARN.

**Comment by maggu2810** [comment]
I did not test it, but "FrameworkEvent" should be handled by `Events.Framework`.
See: http://felix.apache.org/documentation/subprojects/apache-felix-logback.html#mapping-of-osgi-events

So, I assume it is caused by that line: https://github.com/openhab/openhab-distro/blob/0c5f970/distributions/openhab/src/main/resources/userdata/etc/org.ops4j.pax.logging.cfg#L47

**Comment by kaikreuzer** [comment]
> So, I assume it is caused by that line

No, this line is setting the logging for smarthome events, it has nothing to do with framework events.
