### ISSUE TITLE
[paper] BundleException: The bundle class path entry "patch/" could not be found for the bundle

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#66]
When the runtime is started the following stracktrace is logged:

```
17:10:10.255 [INFO ] [org.openhab.ui.paper                 ] - FrameworkEvent INFO - org.openhab.ui.paper
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; type="osgi.bundle"; version:Version="2.5.0.201905102040"; osgi.identity="org.openhab.ui.paper""
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassPathEntry(ClasspathManager.java:174) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.buildClasspath(ClasspathManager.java:152) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.<init>(ClasspathManager.java:81) ~[?:?]
	at org.eclipse.osgi.internal.loader.EquinoxClassLoader.<init>(EquinoxClassLoader.java:43) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:316) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:233) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:595) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getModuleClassLoader(EquinoxBundle.java:588) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getResource(EquinoxBundle.java:530) ~[?:?]
	at org.apache.servicemix.specs.activation.Activator.register(Activator.java:58) ~[?:?]
	at org.apache.servicemix.specs.locator.Activator.bundleChanged(Activator.java:95) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:719) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382) ~[?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

The patch dir is added to the class path for customization support. See also the comments in https://github.com/openhab/openhab-webui/issues/53 . We might also want to restore customization support for the other UIs.

**Comment by kaikreuzer** [comment]
> We might also want to restore customization support for the other UIs.

You mean so that we see such exceptions for all of them...?

**Comment by wborn** [comment]
The customization support was restored for Paper UI but not for Classic UI. I removed the customization support to solve a similar stacktrace for Classic UI in https://github.com/openhab/openhab-webui/pull/22. So if we can fix/suppress this stacktrace we should add customization support back for all UIs that should have this.

**Comment by kaikreuzer** [comment]
I'm not sure we really need any customisation support for Basic/Classic UI - at least as nobody is asking for it.
We should first find a solution for the stacktrace. Suppressing it isn't imho the nicest way to handle it - after all, the message is correct. Maybe we can/should add an empty patch folder in the main bundle to resolve this?

**Comment by maggu2810** [comment]
The message can be suppressed by

```
log:set WARN org.openhab.ui.paper
```

---

BJ Hargrave also suggested the way (add a patch directory to bundle classpath, no patch directory in the host and a patch directory in the fragments) we are using [here](https://stackoverflow.com/questions/21232484/replacing-classes-resources-with-an-osgi-fragment-possible-without-including-a/21241148#21241148).

So, I contacted him if it is still valid.
Here the response (I hope it is okay for him to quote here):

> The event is informative. It may indicate an error in your bundle if you specify a bundle class path entry which is not present in the bundle. Which is why Equinox emits the INFO event. In your case, it
does not indicate an error as you intended to include the "patch" entry which may be provided by a fragment.

> You can request that Equinox change to not emit the INFO event but the spec does say [However, the Framework should publish a Framework Event of type INFO once with an appropriate message for each entry that cannot be located at all.](https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.bundleclasspath)

> So, you should ignore the INFO event. The spec says the framework should publish this event and Equinox does.

**Comment by kaikreuzer** [comment]
> The message can be suppressed by

The problem with this "solution" is that it will also suppress any other INFO/DEBUG logging from the Paper UI...

**Comment by maggu2810** [comment]
I see different options:

* drop customization: bad for me and other ones using customization
* use another customization support: we need someone that invest the time
* keep the log message: bad for openhab distro user
* use a logging configuration that works around the "problem"

Currently there is only one log message (info) that notifies that the bundle has been started in its activate method (I don't care about the sense to log using info that an activation method succeeded).

As we still use "internal" as a package name part for non exported packages and such UIs don't export anything you can simple "workaround" the problem using:

```
log:set WARN org.openhab.ui.paper
log:set INFO org.openhab.ui.paper.internal
```

**Comment by kaikreuzer** [comment]
> you can simple "workaround" the problem using

That might do, yes.
What about my suggestion above "Maybe we can/should add an empty patch folder in the main bundle" - could that be another option or doesn't this work as the folder must only exist exactly once?

**Comment by maggu2810** [comment]
We try to add "patch" to the bundle classpath.
If "patch" does not exist in the host bundle, the lookup continues using the fragments (ordered by the ID).
If "patch" already exists in the host bundle this directory will be added to the class path and there will be no further lookup for its existence in the fragments.

**Comment by kaikreuzer** [comment]
In short: No option, ok.
So let's go with your option (4), but only for Paper UI (and do not (re-)introduce customisation support for Classic/Basic UI as long as nobody needs it).
