### ISSUE TITLE
Paper UI fails to build on 2.5.x branch

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#785]
There seems to be an issue with building Paper UI on the 2.5.x branch. This causes the CI build and release jobs to fail.
Apparently it has issues to launch PhantomJS:

```
[INFO] [10:44:57] Starting 'test'...
[INFO] adding /home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/angular-mocks/angular-mocks.js
[INFO] 2021 10:44:57.463:ERROR [phantomjs.launcher]: Auto configuration failed
[INFO] 139931495173760:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139931495173760:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139931495173760:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139931495173760:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.467:ERROR [launcher]: Cannot start PhantomJS
[INFO] 	Auto configuration failed
[INFO] 139931495173760:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139931495173760:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139931495173760:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139931495173760:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.467:ERROR [launcher]: PhantomJS stdout: 
[INFO] 2021 10:44:57.467:ERROR [launcher]: PhantomJS stderr: Auto configuration failed
[INFO] 139931495173760:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139931495173760:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139931495173760:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139931495173760:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.503:ERROR [phantomjs.launcher]: Auto configuration failed
[INFO] 139998301810304:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139998301810304:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139998301810304:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139998301810304:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.505:ERROR [launcher]: Cannot start PhantomJS
[INFO] 	Auto configuration failed
[INFO] 139998301810304:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139998301810304:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139998301810304:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139998301810304:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.505:ERROR [launcher]: PhantomJS stdout: 
[INFO] 2021 10:44:57.505:ERROR [launcher]: PhantomJS stderr: Auto configuration failed
[INFO] 139998301810304:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139998301810304:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139998301810304:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139998301810304:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.536:ERROR [phantomjs.launcher]: Auto configuration failed
[INFO] 139839153671808:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139839153671808:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139839153671808:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139839153671808:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.537:ERROR [launcher]: Cannot start PhantomJS
[INFO] 	Auto configuration failed
[INFO] 139839153671808:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139839153671808:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139839153671808:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139839153671808:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.537:ERROR [launcher]: PhantomJS stdout: 
[INFO] 2021 10:44:57.537:ERROR [launcher]: PhantomJS stderr: Auto configuration failed
[INFO] 139839153671808:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
[INFO] 139839153671808:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
[INFO] 139839153671808:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
[INFO] 139839153671808:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
[INFO] 
[INFO] 2021 10:44:57.539:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
[INFO] 
[INFO] 
[INFO] 
[INFO] [10:44:57] 'test' errored after 243 ms
[INFO] [10:44:57] Error: 1
[INFO]     at formatError (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/gulp/bin/gulp.js:169:10)
[INFO]     at Gulp.<anonymous> (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/gulp/bin/gulp.js:195:15)
[INFO]     at Gulp.emit (events.js:182:13)
[INFO]     at Gulp.Orchestrator._emitTaskDone (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/orchestrator/index.js:264:8)
[INFO]     at /home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/orchestrator/index.js:275:23
[INFO]     at finish (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/orchestrator/lib/runTask.js:21:8)
[INFO]     at cb (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/orchestrator/lib/runTask.js:29:3)
[INFO]     at removeAllListeners (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/karma/lib/server.js:380:7)
[INFO]     at Server.<anonymous> (/home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/node_modules/karma/lib/server.js:391:9)
[INFO]     at Object.onceWrapper (events.js:273:13)
[INFO]     at Server.emit (events.js:187:15)
[INFO]     at emitCloseNT (net.js:1659:8)
[INFO]     at process._tickCallback (internal/process/next_tick.js:63:19)
[INFO] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! org.openhab.ui.paper@2.5.0 build: `gulp default`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the org.openhab.ui.paper@2.5.0 build script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/jenkins/jenkins-agent1/workspace/openHAB2.5.x-WebUI/bundles/org.openhab.ui.paper/npm_cache/_logs/2021-01-10T10_44_57_580Z-debug.log
```

I have the same issue when building the branch locally.

See: 

* https://ci.openhab.org/job/openHAB2.5.x-WebUI/
* https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/

**Comment by kaikreuzer** [comment]
The interesting thing is that there haven't been any new commits to that branch, so it might be due to some external changes in npm dependencies... @ghys You're expertise would be highly welcome here :-)

**Comment by ghys** [comment]
Seems like a common problem.

Maybe try adding this variable to the build environment:

https://help.nextcloud.com/t/auto-configuration-failed/35721/3

**Comment by wborn** [comment]
My computer does not become any more enthusiastic with that variable set. :wink:

**Comment by ghys** [comment]
Bummer. If we can't solve that easily, and Paper UI is deprecated, what about... bypassing the tests? 🙂

**Comment by kaikreuzer** [comment]
Sounds like a plan - how does one do this...?

**Comment by wborn** [comment]
I'll close this issue since there won't be any 2.5.x releases due to the Bintray sunset.
