### ISSUE TITLE
[PaperUI] Error message for "patch/" on-start

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-webui#97]
The following error is present every time I start OH.  It is the absolute first thing that hits openhab.log every time.

2019-08-09 08:04:22.440 [INFO ] [org.openhab.ui.paper                ] - FrameworkEvent INFO - org.openhab.ui.paper
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; type="osgi.bundle"; version:Version="2.5.0.201908010725"; osgi.identity="org.openhab.ui.paper""
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassPathEntry(ClasspathManager.java:174) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.buildClasspath(ClasspathManager.java:152) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.<init>(ClasspathManager.java:81) ~[?:?]
        at org.eclipse.osgi.internal.loader.EquinoxClassLoader.<init>(EquinoxClassLoader.java:43) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:316) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:233) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.searchHooks(BundleLoader.java:503) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findResource(BundleLoader.java:600) ~[?:?]
        at org.eclipse.osgi.internal.loader.buddy.DependentPolicy.loadResource(DependentPolicy.java:82) ~[?:?]
        at org.eclipse.osgi.internal.loader.buddy.PolicyHandler.doBuddyResourceLoading(PolicyHandler.java:157) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findResource(BundleLoader.java:649) ~[?:?]
        at org.eclipse.osgi.internal.loader.buddy.DependentPolicy.loadResource(DependentPolicy.java:82) ~[?:?]
        at org.eclipse.osgi.internal.loader.buddy.PolicyHandler.doBuddyResourceLoading(PolicyHandler.java:157) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findResource(BundleLoader.java:649) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.getResource(ModuleClassLoader.java:200) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.getResource(EquinoxBundle.java:532) ~[?:?]
        at org.apache.servicemix.specs.activation.Activator.register(Activator.java:58) ~[?:?]
        at org.apache.servicemix.specs.locator.Activator.start(Activator.java:70) ~[?:?]
        at org.apache.servicemix.specs.activation.Activator.start(Activator.java:46) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) ~[?:?]
        at org.eclipse.osgi.container.Module.doStart(Module.java:581) ~[?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:449) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]

**Comment by openhab-5iver** [comment]
https://github.com/openhab/openhab-distro/pull/910

The latest snapshot and 2.5M2 have this corrected. Well... hidden. What version of OH are you using?

**Comment by morph166955** [comment]
Currently on 1655.

**Comment by morph166955** [comment]
Updated to M2.  Still doing it.

**Comment by openhab-5iver** [comment]
The fix is just a change to the logging level. You haven't answered how you've done your upgrade, but something is preventing the logging levels from being updated. This is very easy to do manually.

**Comment by morph166955** [comment]
Upgrade was done through apt.  Starting at M1 I updated to ~1630 (I don't remember exactly which one, it was one of the first that the builds started working again).  I've then (through apt) been updating about weekly until getting to 1655 and now M2.

**Comment by wborn** [comment]
The default logging configuration with openHAB 2.5.0.M2 is:

```
openhab> log:list
Logger                                             │ Level
───────────────────────────────────────────────────┼──────
ROOT                                               │ WARN
javax.jmdns                                        │ ERROR
javax.mail                                         │ ERROR
org.apache.karaf.jaas.modules.audit                │ INFO
org.apache.karaf.kar.internal.KarServiceImpl       │ ERROR
org.apache.karaf.shell.support                     │ OFF
org.apache.sshd                                    │ WARN
org.eclipse.lsp4j                                  │ OFF
org.eclipse.smarthome                              │ INFO
org.jupnp                                          │ ERROR
org.openhab                                        │ INFO
org.openhab.ui.paper                               │ WARN
org.openhab.ui.paper.internal                      │ INFO
org.ops4j.pax.url.mvn.internal.AetherBasedResolver │ ERROR
org.ops4j.pax.web.pax-web-runtime                  │ OFF
smarthome.event                                    │ INFO
smarthome.event.InboxUpdatedEvent                  │ ERROR
smarthome.event.ItemAddedEvent                     │ ERROR
smarthome.event.ItemRemovedEvent                   │ ERROR
smarthome.event.ItemStateEvent                     │ ERROR
smarthome.event.ThingAddedEvent                    │ ERROR
smarthome.event.ThingRemovedEvent                  │ ERROR
smarthome.event.ThingStatusInfoEvent               │ ERROR
```

So if for some reason `userdata/etc/org.ops4j.pax.logging.cfg` wasn't updated (e.g. because of rejecting changes during the update), execute the following commands on the [Karaf Console](https://www.openhab.org/docs/administration/logging.html#karaf-console):

```bash
log:set WARN org.openhab.ui.paper
log:set INFO org.openhab.ui.paper.internal
```


Another way is to stop openHAB and add the following to `userdata/etc/org.ops4j.pax.logging.cfg`:

```properties
log4j2.logger.paperui.name = org.openhab.ui.paper
log4j2.logger.paperui.level = WARN
log4j2.logger.paperuiint.name = org.openhab.ui.paper.internal
log4j2.logger.paperuiint.level = INFO
```

Then after restarting those loggers will be set to the right log level. The exception will still show after the first restart but should be gone with the second restart.

You can also replace the whole file with the defaults that are available in this [org.ops4j.pax.logging.cfg](https://raw.githubusercontent.com/openhab/openhab-distro/master/distributions/openhab/src/main/resources/userdata/etc/org.ops4j.pax.logging.cfg).

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
